#!/usr/bin/env python

# Project settings.
PROJECT_NAME = 'electris'
DATABASE_FILENAME = 'electris.db'
POLLING_INTERVAL = 15

# Constants for Electris the Web app.
PRESIDENT_HEADER = ['id', 'stateface', 'name', 'abbr', 'electoral_votes', 'polls_close', 'prediction', 'call', 'called_at', 'called_by', 'total_precincts', 'precincts_reporting', 'rep_vote_count', 'dem_vote_count']
PREDICTION_OPTIONS = [('sd', 'Solid Democrat'), ('ld', 'Leaning Democrat'), ('t', 'Tossup'), ('lr', 'Leaning Republican'), ('sr', 'Solid Republican')]
RESULT_OPTIONS = [('d', 'Democrat'), ('u', 'Undecided'), ('r', 'Republican')]

# Constants for the BigBoard Web app.
HOUSE_SENATE_HEADER = [
    'state_postal',
    'state_name',
    'office_code',
    'district_id',
    'office_name',
    'district_name',
    'precincts_reporting',
    'total_precincts',
    'ap_npid',
    'first_name',
    'last_name',
    'middle_name',
    'junior',
    'use_junior',
    'incumbent',
    'party',
    'vote_count',
    'ap_winner',
    'ap_winner_time',
    'npr_winner',
    'npr_winner_time'
]
HOUSE_DISTRICTS = [
    u'HI 1',
    u'HI 2',
    u'CT 1',
    u'CT 3',
    u'CT 2',
    u'CT 5',
    u'CT 4',
    u'PA 9',
    u'PA 8',
    u'MD 8',
    u'MD 7',
    u'MD 6',
    u'MD 5',
    u'MD 4',
    u'MD 3',
    u'MD 2',
    u'MD 1',
    u'AL 3',
    u'AL 2',
    u'AL 1',
    u'AL 7',
    u'AL 6',
    u'AL 5',
    u'AL 4',
    u'CA 34',
    u'CA 35',
    u'CA 36',
    u'CA 37',
    u'CA 30',
    u'CA 31',
    u'CA 32',
    u'CA 33',
    u'CA 38',
    u'CA 39',
    u'MA 2',
    u'MA 3',
    u'MA 1',
    u'MA 6',
    u'MA 7',
    u'MA 4',
    u'MA 5',
    u'MA 8',
    u'MA 9',
    u'TN 6',
    u'TN 7',
    u'TN 4',
    u'TN 5',
    u'TN 2',
    u'TN 3',
    u'TN 1',
    u'TN 8',
    u'TN 9',
    u'GA 1',
    u'GA 2',
    u'GA 3',
    u'GA 4',
    u'GA 5',
    u'GA 6',
    u'GA 7',
    u'GA 8',
    u'GA 9',
    u'AZ 5',
    u'AZ 4',
    u'AZ 7',
    u'AZ 6',
    u'AZ 1',
    u'AZ 3',
    u'AZ 2',
    u'AZ 9',
    u'AZ 8',
    u'TX 29',
    u'TX 28',
    u'CO 2',
    u'CO 3',
    u'CO 1',
    u'CO 6',
    u'CO 7',
    u'CO 4',
    u'CO 5',
    u'PA 5',
    u'PA 4',
    u'PA 7',
    u'PA 6',
    u'PA 1',
    u'PA 3',
    u'PA 2',
    u'MT 1',
    u'MN 5',
    u'MN 4',
    u'MN 7',
    u'MN 6',
    u'MN 1',
    u'MN 3',
    u'MN 2',
    u'MN 8',
    u'DE 1',
    u'NY 9',
    u'NY 8',
    u'NY 7',
    u'NY 6',
    u'NY 5',
    u'NY 4',
    u'NY 3',
    u'NY 2',
    u'NY 1',
    u'NC 5',
    u'NC 4',
    u'NC 7',
    u'NC 6',
    u'NC 1',
    u'NC 3',
    u'NC 2',
    u'NC 9',
    u'NC 8',
    u'LA 1',
    u'LA 3',
    u'LA 2',
    u'LA 5',
    u'LA 4',
    u'LA 6',
    u'OK 2',
    u'OK 3',
    u'OK 1',
    u'OK 4',
    u'OK 5',
    u'PA 18',
    u'PA 15',
    u'PA 14',
    u'PA 17',
    u'PA 16',
    u'PA 11',
    u'PA 10',
    u'PA 13',
    u'PA 12',
    u'TX 1',
    u'KS 4',
    u'TX 3',
    u'KS 2',
    u'KS 3',
    u'TX 6',
    u'KS 1',
    u'MI 10',
    u'MI 11',
    u'MI 12',
    u'MI 13',
    u'MI 14',
    u'AK 1',
    u'NV 1',
    u'NV 2',
    u'NV 3',
    u'NV 4',
    u'CA 41',
    u'CA 40',
    u'CA 43',
    u'CA 42',
    u'CA 45',
    u'CA 44',
    u'CA 46',
    u'CA 49',
    u'CA 48',
    u'WA 1',
    u'WA 2',
    u'WA 3',
    u'WA 4',
    u'WA 5',
    u'WA 6',
    u'WA 7',
    u'WA 8',
    u'WA 9',
    u'NH 2',
    u'NH 1',
    u'KY 4',
    u'KY 5',
    u'KY 6',
    u'KY 1',
    u'KY 2',
    u'KY 3',
    u'TX 30',
    u'TX 31',
    u'TX 32',
    u'TX 33',
    u'TX 34',
    u'TX 35',
    u'TX 36',
    u'UT 4',
    u'UT 3',
    u'UT 2',
    u'UT 1',
    u'AR 4',
    u'AR 1',
    u'AR 3',
    u'AR 2',
    u'IL 9',
    u'IL 8',
    u'IL 3',
    u'IL 2',
    u'IL 1',
    u'IL 7',
    u'IL 6',
    u'IL 5',
    u'IL 4',
    u'NE 3',
    u'NE 2',
    u'NE 1',
    u'CA 8',
    u'CA 9',
    u'CA 4',
    u'CA 5',
    u'CA 6',
    u'CA 7',
    u'CA 1',
    u'CA 2',
    u'CA 3',
    u'FL 18',
    u'FL 19',
    u'FL 10',
    u'FL 11',
    u'FL 12',
    u'FL 13',
    u'FL 14',
    u'FL 15',
    u'FL 16',
    u'FL 17',
    u'MO 8',
    u'CA 18',
    u'CA 19',
    u'MO 4',
    u'MO 5',
    u'MO 6',
    u'MO 7',
    u'MO 1',
    u'MO 2',
    u'MO 3',
    u'TX 27',
    u'TX 26',
    u'VA 11',
    u'VA 10',
    u'TX 25',
    u'TX 24',
    u'TX 23',
    u'IA 4',
    u'IA 2',
    u'IA 3',
    u'IA 1',
    u'TX 11',
    u'TX 21',
    u'TX 20',
    u'WY 1',
    u'VA 9',
    u'VA 8',
    u'VA 7',
    u'VA 6',
    u'VA 5',
    u'VA 4',
    u'VA 3',
    u'VA 2',
    u'VA 1',
    u'OH 9',
    u'OH 8',
    u'OH 1',
    u'OH 3',
    u'OH 2',
    u'OH 5',
    u'OH 4',
    u'OH 7',
    u'OH 6',
    u'OR 3',
    u'OR 2',
    u'OR 1',
    u'OR 5',
    u'OR 4',
    u'SD 1',
    u'NC 11',
    u'NC 10',
    u'NC 13',
    u'NC 12',
    u'OH 11',
    u'OH 10',
    u'CA 50',
    u'CA 51',
    u'OH 15',
    u'OH 14',
    u'OH 16',
    u'WV 3',
    u'WV 2',
    u'WV 1',
    u'WV 0',
    u'TX 22',
    u'GA 12',
    u'GA 13',
    u'GA 10',
    u'GA 11',
    u'GA 14',
    u'FL 21',
    u'FL 20',
    u'FL 23',
    u'FL 22',
    u'FL 25',
    u'FL 24',
    u'FL 27',
    u'FL 26',
    u'NY 26',
    u'NY 27',
    u'NY 24',
    u'NY 25',
    u'NY 22',
    u'NY 23',
    u'NY 20',
    u'NY 21',
    u'CA 52',
    u'CA 53',
    u'OH 13',
    u'WI 0',
    u'OH 12',
    u'WI 1',
    u'WI 2',
    u'WI 3',
    u'WI 4',
    u'WI 5',
    u'WI 6',
    u'WI 7',
    u'MI 8',
    u'MI 9',
    u'MI 2',
    u'MI 3',
    u'MI 0',
    u'MI 1',
    u'MI 6',
    u'MI 7',
    u'MI 4',
    u'MI 5',
    u'IL 18',
    u'IL 17',
    u'IL 16',
    u'IL 15',
    u'IL 14',
    u'IL 13',
    u'IL 12',
    u'IL 11',
    u'IL 10',
    u'ND 1',

    u'VT 1',
    u'TX 2',
    u'TX 4',
    u'TX 5',
    u'TX 18',
    u'TX 19',
    u'TX 12',
    u'TX 13',
    u'TX 10',
    u'TX 7',
    u'TX 16',
    u'TX 17',
    u'TX 14',
    u'TX 15',
    u'TX 8',
    u'TX 9',
    u'NJ 12',
    u'NJ 10',
    u'NJ 11',
    u'WI 8',
    u'CA 29',
    u'CA 28',
    u'CA 23',
    u'CA 22',
    u'CA 21',
    u'CA 20',
    u'CA 27',
    u'CA 26',
    u'CA 25',
    u'CA 24',
    u'NM 3',
    u'NM 2',
    u'NM 1',
    u'RI 2',
    u'RI 1',
    u'MS 1',
    u'MS 2',
    u'MS 3',
    u'MS 4',
    u'SC 6',
    u'SC 7',
    u'SC 4',
    u'SC 5',
    u'SC 2',
    u'SC 3',
    u'SC 1',
    u'FL 8',
    u'FL 9',
    u'FL 2',
    u'FL 3',
    u'FL 1',
    u'FL 6',
    u'FL 7',
    u'FL 4',
    u'FL 5',
    u'CA 10',
    u'WA 10',
    u'NY 19',
    u'NY 18',
    u'NY 13',
    u'NY 12',
    u'NY 11',
    u'NY 10',
    u'NY 17',
    u'NY 16',
    u'NY 15',
    u'NY 14',
    u'ID 2',
    u'ID 1',
    u'IN 9',
    u'IN 8',
    u'IN 1',
    u'IN 3',
    u'IN 2',
    u'IN 5',
    u'IN 4',
    u'IN 7',
    u'IN 6',
    u'CA 16',
    u'CA 17',
    u'ME 2',
    u'CA 14',
    u'CA 15',
    u'CA 47',
    u'CA 12',
    u'ME 1',
    u'CA 13',
    u'NJ 4',
    u'NJ 5',
    u'NJ 6',
    u'NJ 7',
    u'NJ 1',
    u'NJ 2',
    u'NJ 3',
    u'CA 11',
    u'NJ 8',
    u'NJ 9'
]
SENATE_DISTRICTS = [
        u'HI 0',
        u'CT 0',
        u'MD 0',
        u'MA 0',
        u'NJ 0',
        u'IN 0',
        u'TN 0',
        u'AZ 0',
        u'PA 0',
        u'MT 0',
        u'MN 0',
        u'DE 0',
        u'NY 0',
        u'TX 0',
        u'NV 0',
        u'ME 0',
        u'WA 0',
        u'UT 0',
        u'NE 0',
        u'CA 0',
        u'MO 0',
        u'VA 0',
        u'OH 0',
        u'ND 0',
        u'VT 0',
        u'NM 0',
        u'RI 0',
        u'MS 0',
        u'FL 0',
        u'WY 0',
    ]
# Constants for static media storage.
import os
if os.environ.get('DEPLOYMENT_TARGET', '') == 'production':
    S3_BUCKET = 'apps.npr.org'
    DEBUG = False
else:
    S3_BUCKET = 'stage-apps.npr.org'
    DEBUG = True
PRESIDENT_S3_KEY = '%s/states.csv' % PROJECT_NAME
PRESIDENT_FILENAME = 'www/states.csv'

HOUSE_S3_KEY = '%s/house.json' % PROJECT_NAME
HOUSE_FILENAME = 'www/house.json'

SENATE_S3_KEY = '%s/senate.json' % PROJECT_NAME
SENATE_FILENAME = 'www/senate.json'

STATIC_URL = 'http://%s/%s' % (S3_BUCKET, PROJECT_NAME)


# Constants for data imports.
STATE_FIELDS = [
    'is_test',
    'election_date',
    'state_postal',
    'county_number',
    'fips',
    'county_name',
    'race_number',
    'office_id',
    'race_type_id',
    'seat_number',
    'office_name',
    'seat_name',
    'race_type_party',
    'race_type',
    'office_description',
    'number_of_winners',
    'number_in_runoff',
    'precincts_reporting',
    'total_precincts'
]
CANDIDATE_FIELDS = [
    'candidate_number',
    'order',
    'party',
    'first_name',
    'middle_name',
    'last_name',
    'junior',
    'use_junior',
    'incumbent',
    'vote_count',
    'is_winner',
    'national_politician_id',
]
NUM_STATE_FIELDS = len(STATE_FIELDS)
NUM_CANDIDATE_FIELDS = len(CANDIDATE_FIELDS)
